# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictacoe', '0002_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='text_to_move',
            new_name='next_to_move',
        ),
    ]
