# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tictacoe', '0004_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AddField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(default=django.utils.timezone.now, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, help_text='Adding a friendly message is never a bad idea', max_length=300, verbose_name='Optional message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select the user you want to play a game with', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recieved', to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
