# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tictacoe', '0005_auto_20161012_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
    ]
