# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tictacoe', '0006_auto_20161012_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
    ]
